#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request using curl,
# it must return a page that contains the string Hello World!

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# nginx service starts
sudo service nginx start

# firewall allows nginx
sudo ufw allow 'Nginx HTTP'

# User gets ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Default index backup
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# nginx restarting
sudo service nginx restart

echo -e "\nCompleted. ✅\n"
