#!/usr/bin/env bash
# Bash script that configure your Nginx server
# to have a custom 404 page that contains
# the string Ceci n'est pas une page
# The page must return an HTTP 404 error code

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# nginx service starting
sudo service nginx start

# nginx allowed on firewall
sudo ufw allow 'Nginx HTTP'

# Users given ownership to easily edit website files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Default index backup
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# New index created
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Setting up /redirect_me to a youtube site
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Set up a 404 page error code
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# nginx restarting
sudo service nginx restart

echo -e "\nCompleted.\n"
