#!/usr/bin/env bash
# script of task 0 less lines, can't use ;&&wget
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
