#!/usr/bin/env bash
# Bash script that displays lines containing the bash word,
# allowing you to get the PID of your Bash process
# You cannot use pgrep, third line of your script
#+ must be # shellcheck disable=SC2009

ps -aux | grep bash
