#!/usr/bin/env bash
# Bash script that displays, to infinity and beyond indefinitely.
# With a sleep 2 in between each iteration.
# I am invincible!!! when receiving a SIGTERM signal

# Function to handle SIGTERM signal
function handle_sigterm {
  echo "I am invincible!!!"
  exit 0
}

# Set up trap for SIGTERM
trap 'handle_sigterm' SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
  echo "To infinity and beyond"
  sleep 2
  echo "I am invincible!!!"
done
