#!/usr/bin/env bash
# This script that loops "Best School" from 1 to 10 and "bad luck", "good luck" for the 4th and 8th iteration respectively

line_count=0

while [ $line_count -le 9 ]
do
    if [ $line_count -eq 3 ]
    then
        echo "bad luck"
    elif [ $line_count -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((line_count++))
done
