#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
# Displays hours from 0 to 12
# Displays minutes from 1 to 59

num_of_hour=0

while [ $num_of_hour -le 12 ]
do
  echo "Hour: $num_of_hour"
  min=1
  while [ $min -le 59 ]
  do
    echo "$min"
    (( min++ ))
  done
  (( num_of_hour++ ))
done
