#!/usr/bin/env bash
# Bash script that configures the container,
# so nginx runs as nginx user and listens on all active IPs on port 8080

pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
