#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server
# using the private key ~/.ssh/school with the user ubuntu
# Only use ssh single-character flags, can't use -l
# You do not need to handle the case of a private key protected by a passphrase
ssh ubuntu@100.25.47.123 -i ~/.ssh/school
